### ISSUE TITLE
Are examples in paper cherry picked?

### ISSUE THREAD

**Issue by gstoica27** [energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch#4]
Hi, 

Thanks for this work and the open sourcing of everything! 

I've been playing around a little bit with the "demo" on huggingface, and unfortunately (for some reason) am finding that the images generated by the model are significantly worse than the apparent quality described in the paper. 

For instance, I have generated several images using the 4th sentence from figure 3, but have yet to obtain an image that is of the quality in the paper. Here are a couple examples:
<img width="1266" alt="Screen Shot 2022-06-15 at 10 23 48 PM" src="https://user-images.githubusercontent.com/14844582/173977835-1f2c752f-c030-45f0-829c-3a18fb47a6d8.png">
<img width="1268" alt="Screen Shot 2022-06-15 at 10 35 03 PM" src="https://user-images.githubusercontent.com/14844582/173978960-348011d8-51f1-424b-aef5-31f028ab5c3a.png">

In the first image the car is at best "barely" behind the tree, though it looks to be more in line or to the side of it. And in the second image, the car is nowhere to be seen (and the blue thing is not exactly indicative of a bird)....

Moreover, I have been toying simpler sentences (e.g. "A red car behind a tree") and the generated images are not very accurate - at least to the degree that I may expect. Here is an example - though for the most part from my anecdotal findings this behavior is fairly consistent.

<img width="1264" alt="Screen Shot 2022-06-15 at 10 21 54 PM" src="https://user-images.githubusercontent.com/14844582/173978098-28cb69ae-31ed-45e5-8b34-4fe537b68e48.png">

The model gets "red car" and "tree", but the relationship between the objects is not accurate. This happens fairly frequently in image generation. It is rare when the relationship "behind" is satisfied.

I really like the ideas proposed in this work, and want to investigate how to extend it further, but it is somewhat concerning that the generated image quality here is so much worse than what seems to be marketed in the paper.

Perhaps there is something I am doing wrong? E.g. maybe the model is brittle to the type of syntax required when inputting prompts? Or the order of the prompts? Or something else? 

I would greatly appreciate any thoughts or help on this - I really want to be able to replicate the types of images shown in the submission.

Thanks!

**Comment by yilundu** [comment]
Hi,

Thank you for your interest and for taking time to try out our demo and paper. For natural language guided generations,
we utilized the small GLIDE model released by OpenAI. Since the model is not trained on much data, the underlying image
generations given certain natural language descriptions is incorrect (such as a red car behind a tree).  In order for our model
to compose well, the GLIDE model must be able to accurately represent each component of the text sentence correctly (also discussed in the limitations section).  Thus, when choosing prompts to show -- we had to find ones that the GLIDE model could accurately represent (which is also why many natural language phrases do not compose as well -- you indeed have to chose a phrasing of sentence so that the GLIDE model generates good images given the phrasing).

In addition, the behavior of composition depend on hyperparameters that are not provided in the Hugginface demo. If you use the Colab demo of composable GLIDE generation -- both increasing the classifier free guidance scale and increasing the underlying number of sampling steps will improve the compositional performance.

Finally, in our paper, we observed very reliable performance  when composing block positions, relations, and facial attributes, where we trained each individual model. These models are not available yet, but we will release them soon.

Happy to discuss more or answer any other questions you have!
