### ISSUE TITLE
[Question] How to train the model with multi GPUs

### ISSUE THREAD

**Issue by zzysay** [energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch#5]
Hi there,

Thanks for open source and it is really an excellent work!

I am trying to train a text-conditioned GLIDE model with MS-COCO dataset, following the command in the readme, but it seems that only one (the first) GPU is used for the training, even though I modify the command to ```CUDA_VISIBLE_DEVICES=0,1 python ...```. Is there anything wrong with my usage?

Looking frowned for your reply!

**Comment by nanlliu** [comment]
You can check out `mpiexec` usage from https://github.com/openai/improved-diffusion.
If `mpiexec` doesn't work,  you might be able to set up distributed training using standard pytorch approach.
This should be quite simple.

**Note: this is just our version of GLIDE since the GLIDE codebase isn't released.**

**Comment by zzysay** [comment]
Thanks very much, it completely solves my confusion!
